### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by MarketingPip** [shaunbharat/render-gfm#1]
Might be a long shot here - but assuming you would be interested in contributing to Markdown Tag?

Tho we would be not using the API to get Markdown. Looking forward to getting in touch if interested!  Feel free to drop contact details or even open up a repo & invite me in their and we can chat via issues in their to avoid spam in this repo (my apologizes).

**Comment by shaunbharat** [comment]
Hey, I would love to help contribute to Markdown-Tag! I can share more details in the morning, since it's pretty late here. I'll see what I can help out with to contribute to your repo.

**Comment by shaunbharat** [comment]
Okay, do I looked at your todo list, and checked some stuff out. Whenever I have time during the week, I'll keep working on some changes locally, and see what I can add. I don't mind chatting in this issue thread, but I can drop an email later if anything.

**Comment by shaunbharat** [comment]
Thanks for inviting me to contribute @MarketingPip !

**Comment by MarketingPip** [comment]
@shaunbharat Thanks for being willing to improve this! I did see another fork with someone making some changes but as said - in terms of general structure for the project. Hoping other developers can give some insight on what changes SHOULD be done. And hopefully we can start getting some discussions on the repo with anyone making changes / enhancements so we know are working on etc / so nobody is re-writing the same functions.  

Keep in mind that to do list in pretty bare! But I just opened up discussions under the repo so we can chat there so things are visible there to other developers. Tho some suggestions to discussion layout would be appreciated! 

[https://github.com/MarketingPipeline/Markdown-Tag/discussions](https://github.com/MarketingPipeline/Markdown-Tag/discussions ) 

Closing this & hoping to meet you there!

**Comment by shaunbharat** [comment]
Hey! So I know you've probably been expecting some contributions to the project for some time, but of course I've been busy with a lot of other work.

Of course I'll work on some changes whenever I can on the side. Just so you know I haven't forgotten about anything!

But I know @DarkenLM has opened a huge pull request, and it brings a lot to the project. So it's great that you do have some activity on the repository!

**Comment by MarketingPip** [comment]
@shaunbharat Hey no worries & no expectations at all! More than happy to have contributors willing to help take any time they have to help improve this project for everyone that uses it. @DarkenLM has been working a lot on the project so I don't want to keep bugging him with more work etc but there is some changes you can address / make to his commit if you are willing (or have time to do so!) 

You can find the work (Syntax Highlighting GFM) needed to be added to his pull request in my comment at the bottom below here  - [Pull Request #7](https://github.com/MarketingPipeline/Markdown-Tag/pull/7)

Your CSS might be improved better than the one provided - but that will be up to you to make final decision on. 

Keep in mind - a replace function for inputs <code>- [ ] </code> needs created if you do not have one already. 


Tho if you do take it on - obviously give him (@DarkenLM) a heads up so nobody is repeating the same jobs that need done! 

Another thing I mentioned to @DarkenLM looking for options to keep the `<md>` tag  - just to relay the whole conversation instead of explaining -


@DarkenLM posted : 

```
In my opinion, attempting to replace all instances of would be bad performance-wise, as in order to ensure that the tag is syntactically correct, one would need to replicate the entire DOM rendering, which will add uncecessary overhead.

If we choose to focus on performance, I suggest we simply accept that the Custom Element will require an hyphen on it's name.

```


@MarketingPip replied
```

[https://stackoverflow.com/questions/65238318/how-to-use-custom-elements-without-hyphen-in-their-name](https://stackoverflow.com/questions/65238318/how-to-use-custom-elements-without-hyphen-in-their-name)



In terms of performance we will face a FOUC but this can be prevented.


[https://stackoverflow.com/questions/46175558/preventing-fouc-when-calling-css-through-a-javascript](https://stackoverflow.com/questions/46175558/preventing-fouc-when-calling-css-through-a-javascript)

I think this needs looked into with options with a work around to make it possible before making any changes to the project. 
```



Hope all is well!

**Off-topic:** don't know the languages you are fluent in but when Pull Request is ready. I would like to provide some translations of the documentation / repo. They will be automatically created but just want to try & ensure they are correct. So any help in that would be more than appreciated (if you speak something other than English)



**_ps;_** I did see your changes / improvements too on his commit already for spelling etc too - so don't think your work doesn't go unnoticed or appreciated!  :heart:
