### ISSUE TITLE
Fails on WIndows: Make sure the path is correct/valid!

### ISSUE THREAD

**Issue by iki** [shaunbharat/render-gfm#4]
`There was an error trying to render the Markdown file. Make sure the path is correct/valid!`

**Comment by shaunbharat** [comment]
I'll try to replicate this issue when I have time. Can you tell me:

- What directory you're running the CLI in
- What path you're inputting as the Markdown file

**Comment by shaunbharat** [comment]
I was able to reproduce this issue while trying to reproduce issue #6. It seems like there might be something wrong with the dependencies render-gfm uses, or something else. Thus, I'm reopening this issue and I'll see if I can get time to try and fix it.
